"""
Django settings for project4 project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent
DEFAULT_PROFILE_PICTURE = "network/images/default_profile.png"
DEFAULT_PROFILE_PICTURE_DARK = "network/images/default_profile_dark.png"
DATABASE_URL = os.environ.get("DATABASE_URL")
db_config = dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
is_local_dev = os.environ.get("IS_LOCAL_DEV") == "True"

if is_local_dev and db_config.get("HOST") == "db":
    db_config["HOST"] = "localhost"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "default-insecure-key-for-local-dev-only")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

if DEBUG:
    # Github codespaces allowed for easier cross-platform debugging
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".app.github.dev"]
else:
    ALLOWED_HOSTS = ["*"]  # Demo purposes only

INTERNAL_IPS = [
    "127.0.0.1",
    "172.16.0.0/12",
]

SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

CSRF_TRUSTED_ORIGINS = [
    "https://localhost:8000",
    "https://*.app.github.dev",
    "https://*.githubpreview.dev",
    "https://*.githubusercontent.com",
    "https://*.*.app.github.dev",
    "https://*.app.github.dev:8000",
    "https://*.*.app.github.dev:8000",
]

CSRF_COOKIE_PATH = "/"
SESSION_COOKIE_PATH = "/"
CSRF_COOKIE_NAME = "csrftoken"
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_REFERER = None
USE_X_FORWARDED_HOST = True

if is_local_dev:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_DOMAIN = None
    SESSION_COOKIE_DOMAIN = None
else:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_DOMAIN = ".app.github.dev"
    SESSION_COOKIE_DOMAIN = ".app.github.dev"

# Application definition

INSTALLED_APPS = [
    "network",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.staticfiles",
    "django.contrib.messages",
    "versatileimagefield",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if is_local_dev:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "project4.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "network.utils.default_profile_picture",
                "network.utils.default_profile_picture_dark",
            ],
        },
    },
]

WSGI_APPLICATION = "project4.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {"default": db_config}


AUTH_USER_MODEL = "network.User"

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "network" / "static",
]

if DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:  
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media Files (Profile Pictures)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


SECURE_BROWSER_NO_OPEN = True
SECURE_CONTENT_TYPE_NOSNIFF = True

if "test" in sys.argv or "pytest" in sys.modules:
    env_path = Path(BASE_DIR) / ".env.local"
    if env_path.exists():
        load_dotenv(dotenv_path=env_path)

    DATABASE_URL = os.environ.get("DATABASE_URL")
    if DATABASE_URL:
        DATABASES["default"] = dj_database_url.config(
            default=DATABASE_URL, conn_max_age=600
        )
    else:
        raise ImproperlyConfigured(
            "DATABASE_URL not found. Create a .env.local file with DATABASE_URL=postgres://... "
            "or run tests with docker compose -f docker-compose.yml exec web pytest"
        )