# Generated by Django 5.2.3 on 2025-11-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="post_count",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
