# Generated by Django 5.2.3 on 2025-11-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_post_comment_count_post_like_count_user_post_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers_count",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="following_count",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
