# Generated by Django 5.2.8 on 2025-12-04 01:43

import django.core.validators
import django.db.models.functions.text
import network.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("network", "0004_user_followers_count_user_following_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["timestamp", "id"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-timestamp", "-id"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="comment_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="like_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True,
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(message="Invalid email.")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followers_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="following_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="post_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                default="network/images/default_profile.png",
                null=True,
                upload_to=network.models.profile_picture_upload,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True,
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, message="Username must be at least 3 characters."
                    ),
                    django.core.validators.RegexValidator(
                        message="Username can only contain letters, numbers, undescores, or dots.",
                        regex="^[\\w.@+-]+$",
                    ),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-timestamp", "-id"], name="post_cursor_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                django.db.models.functions.text.Lower("username"),
                name="user_username_lower_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                django.db.models.functions.text.Lower("email"),
                name="user_email_lower_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="user_username_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="user_email_ci_unique",
            ),
        ),
    ]
